apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-diff-logger
  namespace: default
data:
  config.yml: |
    differs:
      - groupKind:
          group: "apps"
          kind: "deployment"
        nameFilter: "*"
      - groupKind:
          group: "apps"
          kind: "statefulset"
        nameFilter: "*"
      - groupKind:
          group: "apps"
          kind: "daemonset"
        nameFilter: "*"
      - groupKind:
          group: "batch"
          kind: "cronjob"
        nameFilter: "*"
