apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-diff-logger
  namespace: default
data:
  config.yml: |
    groupKinds:
      - group: "apps"
        kind: "deployment"
        nameFilter: "*"
      - group: "batch"
        kind: "cronjob"
        nameFilter: "test"
