apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-diff-logger
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-diff-logger
subjects:
- kind: ServiceAccount
  name: kube-diff-logger
  namespace: default
roleRef:
  kind: ClusterRole
  name: kube-diff-logger
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: kube-diff-logger
